# Generated by Django 5.1.15 on 2026-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wa_phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('ig_account_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('greeting_message', models.TextField(blank=True)),
                ('closing_message', models.TextField(blank=True)),
                ('handoff_enabled', models.BooleanField(default=False)),
                ('handoff_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
