# Generated by Django 5.1.15 on 2026-06-07 20:06

import apps.tenants.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ig_access_token',
            field=apps.tenants.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wa_access_token',
            field=apps.tenants.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
