# Generated by Django 5.1.15 on 2026-06-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_ig_access_token_tenant_wa_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
