# Generated by Django 5.1.15 on 2026-06-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='wa_phone_number_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
