# Generated by Django 5.1.15 on 2026-06-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('is_start', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FlowOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(max_length=20)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_options', to='flows.flowstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='flows.flowstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='flowstep',
            index=models.Index(fields=['tenant'], name='flows_flows_tenant__9b91ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_start', True)), fields=('tenant',), name='unique_start_step_per_tenant'),
        ),
    ]
