# Generated by Django 5.1.15 on 2026-06-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=16)),
                ('customer_identifier', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('handed_off', 'Handed off')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='flows.flowstep')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('content', models.TextField(blank=True)),
                ('channel', models.CharField(max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['tenant', 'channel', 'customer_identifier'], name='conversatio_tenant__b1cc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'sent_at'], name='conversatio_session_221089_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id__isnull', False)), fields=('session', 'provider_message_id'), name='unique_provider_message_per_session'),
        ),
    ]
