# Generated by Django 5.1.15 on 2026-06-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='awaiting_handoff',
            field=models.BooleanField(default=False),
        ),
    ]
